//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by duff.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDD_LAYERS_PAGE                 101
#define IDS_MAIN_WINDOW_TITLE           101
#define IDD_DUFF_DIALOG                 102
#define IDS_MENU_FILE                   102
#define IDD_FILENAME_LAYER_FORM         103
#define IDS_MAINDIALOG_CURRENT_TASK     103
#define IDD_DIRECTORIES_PAGE            104
#define IDS_MSGBOX_ACCELERATOR_LOAD_ERROR_TEXT 104
#define IDS_MSGBOX_TITLE_ERROR          105
#define IDS_STATUS_IDLE                 106
#define IDS_ANIMATION_FILENAME          107
#define IDS_ANIMATE_CONTROL_LOADED      108
#define IDS_ANIMATE_CONTROL_NOT_LOADED  109
#define IDS_LOG_DATETIME_FORMAT         110
#define IDS_MSGBOX_ARE_YOU_SURE_TEXT    111
#define IDS_MSGBOX_ARE_YOU_SURE_TITLE   112
#define IDS_MSGBOX_NOT_IMPLEMENTED_YET_TITLE 113
#define IDS_SAVELOG_DLG_TITLE           114
#define IDS_DUFF_LOG_DEFAULT_FILENAME   115
#define IDS_SAVELOG_FILENAME_FILTER     116
#define IDS_SAVELOG_FINISHED            117
#define IDS_SAVELOG_ERROR               118
#define IDS_SAVELOG_CANCELLED           119
#define IDS_SAVELOG_FILE_FORMAT         120
#define IDS_STATUS_BUSY                 121
#define IDS_LOGTEXT_SEARCH_STOPPED      122
#define IDS_STATUS_PAUSED               123
#define IDS_STATUS_UNPAUSED             124
#define IDS_MSGBOX_NOT_IMPLEMENTED_YET  125
#define IDS_LOADING_PLUGINS             126
#define IDS_FINISHED_LOADING_PLUGINS    127
#define IDR_MAINFRAME                   128
#define IDS_BAD_FCL_INPUT               128
#define IDR_MENU_MAIN                   129
#define IDS_BAD_DIRECTORY_INPUT         129
#define IDD_DUPLICATES_PAGE             130
#define IDS_BAD_FILTER_INPUT            130
#define IDD_PROCESSES_PAGE              131
#define IDS_BAD_MARKER_INPUT            131
#define IDD_STATUSLOG_PAGE              132
#define IDR_ACCELERATOR                 132
#define IDS_BAD_PROCESSOR_INPUT         132
#define IDD_SELECTIONS_PAGE             133
#define IDS_SAVED_GLOBAL_OPTIONS        133
#define IDR_MENU_DUPLICATES             134
#define IDS_PLUGIN_SEARCHPATH           134
#define IDS_LOADED_PLUGIN               135
#define IDS_SKIPPING_NON_DLL            136
#define IDS_TIME_LIMITED_VERSION        137
#define IDS_COMPILED_ON                 139
#define IDS_VERSION                     140
#define IDD_FILE_DELETE_PROCESS_FORM    141
#define IDS_TIMEOUT_MESSAGE             141
#define IDI_ICON1                       142
#define IDS_SEARCHDIALOG_NOT_FOUND      142
#define IDB_TABIMAGES                   143
#define IDS_SEARCHDIALOG_SEARCH         143
#define IDD_OPTIONS_PAGE                144
#define IDS_COLUMN_SET                  144
#define IDD_FILENAME_SELECTION_FORM     145
#define IDS_STATUS_CREATING_DIR_LIST    145
#define IDD_FILE_MOVE_PROCESS_FORM      146
#define IDS_LOGTEXT_FILE_LIST_GENERATION_STARTED 146
#define IDD_FILE_ATTRIBUTES_FILTER_FORM 147
#define IDB_FOLDERS                     147
#define IDS_STATUS_SEARCHING_FOR_FILES  147
#define IDD_FILE_FILTERS_PAGE           148
#define IDS_LOGTEXT_FILE_LIST_GENERATION_FINISHED 148
#define IDD_FILE_SIZE_FILTER_FORM       149
#define IDS_STATUS_FILTERING            149
#define IDD_FORMVIEW                    150
#define IDD_FILE_LOCATION_MARKER_FORM   150
#define IDS_LOGTEXT_FILTER_STARTED      150
#define IDD_FILE_DATA_LAYER_FORM        151
#define IDD_FILE_TEXT_DATA_LAYER_FORM   151
#define IDS_STATUS_FILTERING_WITH_FILTER 151
#define IDD_OPTIONS_SOUNDS_FORM         152
#define IDS_LOGTEXT_FILTERED_OUT        152
#define IDS_LOGTEXT_FILTER_FINISHED     153
#define IDD_FILE_DATE_FILTER_FORM       154
#define IDS_LOGTEXT_DUPESEARCH_COMPLETE 154
#define IDD_OPTIONS_GENERAL             155
#define IDS_LOGTEXT_DUPELIST_BUILD_STARTED 155
#define IDD_OPTIONS_SELECTIONS          156
#define IDS_STATUS_BUILDING_DUPELIST    156
#define IDD_OPTIONS_PROCESSES           157
#define IDS_LOGTEXT_DUPELIST_BUILD_FINISHED 157
#define IDS_LOGTEXT_MARKING_STARTED     158
#define IDD_DUPE_FIND_DIALOG            159
#define IDS_LOGTEXT_MARKING_FINISHED    159
#define IDD_FILE_DATE_MARKER_FORM       160
#define IDB_DUFF                        160
#define IDS_DUPELIST_CONFIRM_DELETE_SELECTED 160
#define IDD_MARKER_OPTIONS_FORM         161
#define IDR_DUPE_HEADER_MENU            161
#define IDS_CONFIRMATION                161
#define IDD_FILE_SIZE_MARKER_FORM       162
#define IDS_COLUMN_DATE_LAST_ACCESSED   162
#define IDD_FILE_VERSION_MARKER_FORM    163
#define IDS_COLUMN_ATTRIBUTES           163
#define IDD_FILE_MP3DATA_LAYER_FORM     164
#define IDS_COLUMN_DATE_CREATED         164
#define IDD_FILE_CONTENTS_FILTER_FORM   165
#define IDS_NONE                        165
#define IDD_DIALOG1                     166
#define IDD_DEBUG_PAGE                  166
#define IDS_COLUMN_LOCATION             166
#define IDS_COLUMN_DATE_LAST_MODIFIED   167
#define IDS_COLUMN_FILENAME             168
#define IDS_FILENAMEEDIT_BROWSE         169
#define IDS_FILENAMEEDIT_UNDO           170
#define IDS_FILENAMEEDIT_CUT            171
#define IDS_FILENAMEEDIT_COPY           172
#define IDS_FILENAMEEDIT_PASTE          173
#define IDS_FILENAMEEDIT_DELETE         174
#define IDS_FILENAMEEDIT_SELECT_ALL     175
#define IDS_COLUMN_FILE_SIZE            176
#define IDS_COLUMN_TYPE                 177
#define IDS_COLUMN_VERSION              178
#define IDS_COLUMN_FULL_FILENAME        179
#define IDS_HYPERLINK_COPY_ADDRESS      180
#define IDS_HYPERLINK_OPEN_ADDRESS      181
#define IDS_OPTIONS_MARKERS             182
#define IDS_OPTIONS_GENERAL             183
#define IDS_CONFIRM_PROCESS_FULL_SET    184
#define IDS_OPTIONS_PROCESSORS          185
#define IDS_OPTIONS_SOUNDS              186
#define IDS_LOGCOLUMN_DATETIME          187
#define IDS_LOGCOLUMN_DESCRIPTION       188
#define IDS_LOG_CLEARED                 189
#define IDS_ERROR                       190
#define IDS_PLUGINTYPE_PROCESSOR        191
#define IDS_PLUGINTYPE_FILER            192
#define IDS_PLUGINTYPE_MARKER           193
#define IDS_PLUGINTYPE_COMPARISONLAYER  194
#define IDS_PLUGINTYPE_TOOL             195
#define IDS_SEARCHDIALOG_SELECTCOLUMN   196
#define IDC_DUPLICATE_LIST              1000
#define IDC_SELECTION_LIST              1003
#define IDC_LAYER_LIST                  1004
#define IDC_SELECTIONS_MAKE             1005
#define IDC_PROGRESS_ENTIRE             1008
#define IDC_PROGRESS_SUB_1              1010
#define IDC_CURRENT_TASK                1011
#define IDC_TASK_INFO                   1012
#define IDC_PROGRESS_SUB_2              1013
#define IDC_PROCESS_LIST                1017
#define IDC_PERFORM                     1018
#define IDC_SAVE_LOG                    1020
#define IDC_STATUS_LOG                  1021
#define IDC_CLEAR_LOG                   1022
#define IDC_PROPERTYSHEET               1026
#define IDC_LAYER_DESCRIPTION           1027
#define IDC_MATCH_FILENAMES             1029
#define IDC_MATCH_NOT_FILENAME          1030
#define IDC_MATCH_EXTENSIONS            1031
#define IDC_NOCONFIG                    1032
#define IDC_MATCH_NOT_EXTENSIONS        1032
#define IDC_DIRS_INCLUDE                1033
#define IDC_MATCH_WORDS                 1033
#define IDC_DIRS_EXCLUDE                1034
#define IDC_INCLUDE_FILTERS             1034
#define IDC_EXCLUDE_FILTERS             1035
#define IDC_SELECTIONS_CLEAR            1037
#define IDC_INCLUDE_HIDDEN              1039
#define IDC_INCLUDE_SYSTEM              1040
#define IDC_START                       1040
#define IDC_EXIT                        1041
#define IDC_INCLUDE_READONLY            1041
#define IDC_STOP                        1042
#define IDC_RESET                       1043
#define IDC_PROCESS_DESCRIPTION         1044
#define IDC_BROWSE_INCLUDE              1045
#define IDC_BROWSE_EXCLUDE              1046
#define IDC_PERFORM_AUTO                1046
#define IDC_SELECT_AUTO                 1047
#define IDC_CLEAR_RESULTS               1048
#define IDC_GET_VERSIONS                1049
#define IDC_ANIMATE_CONTROL             1050
#define IDC_TOTAL_SIZE                  1051
#define IDC_TOTAL_COUNT                 1052
#define IDC_ICONLOGO                    1053
#define IDC_TOTAL_SELECTED              1053
#define IDC_TOTAL_CHECKED               1054
#define IDC_PAUSE                       1055
#define IDC_SELECTED_SIZE               1055
#define IDC_SAVE                        1056
#define IDC_MARKED_SIZE                 1056
#define IDC_TOTAL_DUPLICATES            1057
#define IDC_TOTAL_DUPE_SIZE             1058
#define IDC_RECYCLE                     1064
#define IDC_DELETE                      1065
#define IDC_DELETE_READONLY             1066
#define IDC_STATUS_GROUP                1067
#define IDC_STATIC_CURRENT_TASK         1068
#define IDC_STATIC_TASK_INFO            1069
#define IDC_STATIC_SUBPROGRESS2         1070
#define IDC_STATIC_SUBPREGRESS1         1071
#define IDC_STATIC_PROGRESS_ENTIRE      1072
#define IDC_FILENAME_SKIP               1073
#define IDC_PROGRESS_UPDATE_INTERVAL    1073
#define IDC_NO_ACCESS_RETRY             1075
#define IDC_SET_PROCESS_WARNING         1076
#define IDC_SELECTION_DESCRIPTION       1077
#define IDC_LONGEST                     1078
#define IDC_SHORTEST                    1079
#define IDC_CONTAIN                     1080
#define IDC_DONTCONTAIN                 1081
#define IDC_LOWERCASE                   1082
#define IDC_UPPERCASE                   1083
#define IDC_ONE                         1084
#define IDC_DIR                         1084
#define IDC_MANY                        1085
#define IDC_BROWSE                      1085
#define IDC_IGNORE                      1086
#define IDC_MOVE_READ_ONLY              1086
#define IDC_PICK                        1087
#define IDC_INCLUDE_ARCHIVE             1087
#define IDC_CONTAINTEXT                 1088
#define IDC_INCLUDE_COMPRESSED          1088
#define IDC_LAYER_INFO_FRAME            1088
#define IDC_CASE_SENSITIVE              1089
#define IDC_LAYER_CONFIG_FRAME          1089
#define IDC_COMPARISON_LAYERS_FRAME     1090
#define IDC_RADIO4                      1091
#define IDC_SYSTEM                      1091
#define IDC_RADIO8                      1092
#define IDC_READ_ONLY                   1092
#define IDC_RADIO7                      1093
#define IDC_COMPRESSED                  1093
#define IDC_RADIO9                      1094
#define IDC_ARCHIVED                    1094
#define IDC_RADIO10                     1095
#define IDC_HIDDEN                      1095
#define IDC_RADIO11                     1096
#define IDC_FILE_FILTERS_FRAME          1096
#define IDC_ENCRYPTED                   1096
#define IDC_FILTER_INFO_FRAME           1097
#define IDC_FILTER_DESCRIPTION          1098
#define IDC_FILTER_CONFIG_FRAME         1099
#define IDC_FILTER_CHECKLIST            1100
#define IDC_LAYER_CHECKLIST             1101
#define IDC_SELECTION_CHECKLIST         1102
#define IDC_PROCESS_CHECKLIST           1103
#define IDC_STATUS                      1104
#define IDC_INCLUDE_DESCRIPTION         1105
#define IDC_SUBDIRS_DESCRIPTION         1106
#define IDC_DIRECTORY_DESCRIPTION       1107
#define IDC_EXCLUDE_BROWSE_DESC         1108
#define IDC_INCLUDE_BROWSE_DESC         1109
#define IDC_DUPLICATE_LIST_FRAME        1110
#define IDC_STATIC_SELECTED             1111
#define IDC_STATIC_COUNT                1112
#define IDC_STATIC_SIZE                 1113
#define IDC_THREAD_PRIORITY             1114
#define IDC_STATIC_SELECTED_SIZE        1114
#define IDC_STATIC_MARKED_SIZE          1115
#define IDC_FILTER_TYPE                 1116
#define IDC_STATIC_TOTAL_DUPE_SIZE      1116
#define IDC_VALUE1                      1117
#define IDC_VALUE2                      1118
#define IDC_STATIC_AND                  1119
#define IDC_STATIC_BYTES                1120
#define IDC_SELECTION_FRAME             1121
#define IDC_SELECTION_INFO_FRAME        1122
#define IDC_SELECTION_CONFIG_FRAME      1123
#define IDC_PROCESS_FRAME               1124
#define IDC_PROCESS_INFO_FRAME          1125
#define IDC_PROCESS_CONFIG_FRAME        1126
#define IDC_STATUS_LOG_FRAME            1127
#define IDC_COMPARISON_MODE_BINARY      1131
#define IDC_COMPARISON_MODE_TEXT        1132
#define IDC_FRAME                       1133
#define IDC_AUTO_UNMARK                 1136
#define IDC_PROCESS_AUTO                1137
#define IDC_PROCESS_AUTO_PERFORM        1137
#define IDC_OPTIONS                     1139
#define IDC_OPTION_LIST                 1140
#define IDC_YES_TO_ALL                  1141
#define IDC_LAYER_MOVE_UP               1143
#define IDC_LAYER_MOVE_DOWN             1144
#define IDC_STATIC_ORDER                1145
#define IDC_DUPLICATE_TREE              1146
#define IDC_STATIC_FRAME                1147
#define IDC_EDIT1                       1148
#define IDC_TEXT                        1148
#define IDC_PATH                        1148
#define IDC_WORD_COUNT                  1148
#define IDC_CONTENT_STRING              1148
#define IDC_TOOLTIP_FORMAT              1148
#define IDC_EDIT2                       1149
#define URL_HOMEPAGE                    1149
#define IDC_FOUND_DUPLICATE             1149
#define IDC_TYPO_COUNT                  1149
#define URL_SIZELIB                     1150
#define IDC_PROCESS_COMPLETE            1150
#define IDC_INCLUDE_DIRECTORIES_LIST    1153
#define IDC_REMOVE_SELECTED_INCLUDE_DIRECTORY 1154
#define IDC_FILE_MASKS                  1155
#define IDC_EXCLUDE_DIRECTORIES_LIST    1156
#define IDC_REMOVE_SELECTED_EXCLUDE_DIRECTORY 1158
#define IDC_FILENAME                    1159
#define IDC_WHATFILES_OPTION1           1162
#define IDC_WHATFILES_OPTION2           1163
#define IDC_NEWLINE                     1164
#define IDC_LINE_FORMAT                 1165
#define URL_CHYPERLINK                  1166
#define URL_VERSIONINFO                 1167
#define IDC_DATETIME_CREATED1           1168
#define IDC_FILTERTYPE_CREATED          1169
#define IDC_DATETIME_CREATED2           1170
#define IDC_DATETIME_MODIFIED1          1173
#define IDC_FILTERTYPE_MODIFIED         1174
#define IDC_DATETIME_MODIFIED2          1175
#define IDC_DATETIME_ACCESSED1          1178
#define IDC_FILTERTYPE_ACCESSED         1179
#define IDC_DATETIME_ACCESSED2          1180
#define IDC_OPTION_CREATED              1186
#define IDC_OPTION_MODIFIED             1187
#define IDC_OPTION_ACCESSED             1188
#define IDC_AND_CREATED                 1189
#define IDC_AND_MODIFIED                1190
#define IDC_AND_ACCESSED                1191
#define IDC_IGNORE_TIME_CREATED         1192
#define IDC_IGNORE_TIME_MODIFIED        1193
#define IDC_COMPILED_DATE               1193
#define IDC_IGNORE_TIME_ACCESSED        1194
#define IDC_STATIC_CHECKED              1194
#define IDC_STATIC_DUPLICATES           1195
#define IDC_AUTOSCROLL_DUPE_LIST        1206
#define IDC_BROWSE1                     1209
#define IDC_PLAY1                       1210
#define IDC_BROWSE2                     1211
#define IDC_PLAY2                       1212
#define IDC_ENABLED                     1213
#define IDC_OPTION_FRAME                1216
#define IDC_OPTION_TITLE                1217
#define IDC_ABORT_CHANGES               1218
#define IDC_APPLY_CHANGES               1219
#define IDC_CLEAR_MARKS                 1220
#define IDC_RADIO_LOGIC_AND             1221
#define IDC_RADIO_LOGIC_OR              1222
#define IDC_STATIC_LOGIC                1224
#define IDC_REMOVE_ALL_DIRECTORIES      1225
#define IDC_STATIC_LIST_INFO            1226
#define IDC_RADIO1                      1231
#define IDC_DIRECTION_UP                1231
#define IDC_MOST_RECENTLY_CREATED       1231
#define IDC_NODIFF_MARK_NONE            1231
#define IDC_FILE_VERSION_OLDEST         1231
#define IDC_CONTAINS_DATA               1231
#define IDC_FILE_VERSION_NEWEST         1232
#define IDC_DIRECTION_DOWN              1232
#define IDC_RADIO2                      1232
#define IDC_DOES_NOT_CONTAIN_DATA       1232
#define IDC_LEAST_RECENTLY_CREATED      1232
#define IDC_PRODUCT_VERSION_OLDEST      1233
#define IDC_MATCHCASE                   1233
#define IDC_MOST_RECENTLY_MODIFIED      1233
#define IDC_PRODUCT_VERSION_NEWEST      1234
#define IDC_WHOLE_WORD_ONLY             1234
#define IDC_LEAST_RECENTLY_MODIFIED     1234
#define IDC_MOST_RECENTLY_ACCESSED      1235
#define IDC_SELECT_ALL                  1236
#define IDC_LEAST_RECENTLY_ACCESSED     1236
#define IDC_SELECT_FIRST                1237
#define IDC_NODIFF_MARK_FIRST           1242
#define IDC_MODE_SINGLE                 1243
#define IDC_MODE_MULTIPLE               1244
#define IDC_SUBDIRS                     1245
#define IDC_INCLUDE_PATH                1247
#define IDC_IN_DIR                      1248
#define IDC_NOTIN_DIR                   1249
#define IDC_VERSION                     1250
#define IDC_EMAIL                       1251
#define IDC_ATTRIBUTES_LIST             1253
#define IDC_ATTRIBUTES_ANY              1254
#define IDC_CLEAR_CURSEL                1256
#define IDC_OPTION                      1257
#define IDC_SMALLEST                    1257
#define IDC_BIGGEST                     1258
#define IDC_SUBRANGE2                   1274
#define IDC_SUBRANGE1                   1275
#define IDC_RANGE_ENTIRE                1276
#define IDC_SLIDER                      1277
#define IDC_SIZETEXT                    1278
#define IDC_STATIC_COMMON_WORDS         1279
#define IDC_CHECK1                      1280
#define IDC_CHECK2                      1281
#define IDC_TEXT_ENCODING_FORMATS       1282
#define IDC_FILES                       1283
#define IDC_READ_FILES                  1284
#define IDC_FILEINFO_COUNT              1285
#define IDC_LICENSE_TYPE                1286
#define IDC_SHOW_TOOLTIPS               1287
#define IDC_TOOLTIP_TEXTS               1289
#define IDC_STATIC_TOOLTIP_FORMAT       1290
#define IDC_STATIC_TOOLTIP_TEXTS        1291
#define IDC_COLUMNS                     1292
#define IDC_MARK_AT_LEAST_ONE           1293
#define IDC_LIST1                       1294
#define IDC_PLUGIN_INFORMATION          1294
#define IDC_NOT                         1295
#define IDC_COPYRIGHT                   1296
#define IDC_TEST                        1297
#define IDM_FILE_SAVE                   32771
#define IDM_HELP_ABOUT                  32772
#define IDM_FILE_EXIT                   32773
#define IDM_SEARCH_START                32774
#define IDM_SEARCH_PAUSE                32775
#define IDM_SEARCH_STOP                 32776
#define IDM_VIEW_LAYERS                 32777
#define IDM_VIEW_DIECTORIES             32778
#define IDM_VIEW_DUPLICATES             32779
#define IDM_VIEW_SELECTIONS             32780
#define IDM_VIEW_PROCESSES              32781
#define IDM_VIEW_LOG                    32782
#define ID_FILE_CLEAR_RESULTS           32784
#define IDM_FILE_SAVELOG                32785
#define ID_OPENDIRS                     32787
#define ID_OPENFILES                    32788
#define ID_MARK                         32789
#define ID_UNMARK                       32790
#define ID_INVERTMARKS                  32791
#define ID_REMOVEFROMLIST               32792
#define ID_PROPERTIES                   32793
#define ID_PROCESSFILES_DELETE          32794
#define ID_PROCESSFILES_MOVETODIR       32795
#define ID_PROCESSFILES_SAVETOFILE      32796
#define ID_PROCESSFILES_CHANGEATTRIBUTES 32797
#define ID_MARKSPECIAL_MARKFILESWITHLONGESTFILENAME 32798
#define ID_MARKSPECIAL_MARKOLDESTFILES  32799
#define ID_MARKSPECIAL_MARKSMALLESTFILES 32800
#define IDM_VIEW_OPTIONS                32801
#define IDM_VIEW_FILE_FILTERS           32802
#define IDM_HELP_INDEX                  32804
#define ID_COPYFILENAME                 32805
#define ID_COPYDIRECTORYNAME            32806
#define ID_COPYFULLFILENAME             32807
#define IDM_FILE_SAVE_GLOBAL            32808
#define ID_MARK_ALL                     32809
#define ID_MARK_NONE                    32810
#define ID_REMOVE_ALL                   32819
#define ID_REMOVE_NONSELECTED           32820
#define ID_SELECT_ALL                   32821
#define ID_SELECT_NONE                  32822
#define ID_INVERTSELECTION              32823
#define ID_PERFORM_CHECKED_SELECTIONS   32824
#define ID_FIND                         32825
#define IDM_TOOLS_FIND_FILE             32826
#define IDM_TOOLS_COMPARE_DIRS          32827
#define IDM_COLUMN_FIXED_WIDTH          32838
#define IDM_COLUMN_VARIABLE_WIDTH       32839
#define IDM_COLUMN_AUTO_WIDTH           32840
#define IDM_COPY_ENTIRE_LIST            32841
#define IDM_COPY_ALL_VISIBLE_COLUMNS    32842
#define IDM_FILE_EXPORT_CSV             32843
#define IDM_FILE_EXPORT_DUPLIC8         32845
#define IDM_FILE_IMPORT_DUPLIC8         32846
#define IDM_FILE_EXPORT_FND             32847
#define IDM_FILE_IMPORT_FND             32848

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        168
#define _APS_NEXT_COMMAND_VALUE         32850
#define _APS_NEXT_CONTROL_VALUE         1298
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
